[package]
name = "rustmux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "*"
libc = "*"
term_size = "*"
anyhow = "*"
termios = "*"
ncurses = "*"
